-- Create email verification codes table
CREATE TABLE IF NOT EXISTS public.email_verification_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(10) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_verification_codes_email ON public.email_verification_codes(email);
CREATE INDEX IF NOT EXISTS idx_email_verification_codes_code ON public.email_verification_codes(code);
CREATE INDEX IF NOT EXISTS idx_email_verification_codes_expires_at ON public.email_verification_codes(expires_at);

-- Add RLS policies
ALTER TABLE public.email_verification_codes ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own verification codes
CREATE POLICY "Users can view own verification codes" ON public.email_verification_codes
  FOR SELECT USING (auth.email() = email);

-- Policy: Users can only insert their own verification codes
CREATE POLICY "Users can insert own verification codes" ON public.email_verification_codes
  FOR INSERT WITH CHECK (auth.email() = email);

-- Policy: Service role can do everything (for Edge Functions)
CREATE POLICY "Service role full access" ON public.email_verification_codes
  FOR ALL USING (auth.role() = 'service_role');

-- Function to clean up expired codes
CREATE OR REPLACE FUNCTION cleanup_expired_verification_codes()
RETURNS void AS $$
BEGIN
  DELETE FROM public.email_verification_codes 
  WHERE expires_at < NOW() OR used = TRUE;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to automatically clean up old codes (optional)
-- You can call this function periodically or set up a cron job
